In [11]:
import pandas as pd
import sys
sys.path.insert(0, '../src')

import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import seaborn as sns

sns.set_theme(style="whitegrid", palette="muted", font_scale=1.1)
plt.rcParams["figure.dpi"] = 120
pd.set_option("display.max_columns", None)

In [14]:
from download import download_all

# select date range
START = "2026_04_10"
END  = "2026_04_10"

download_all(tables=["trains"], start_date=START, end_date=END)
download_all(tables=["stations"], start_date=START, end_date=END)
download_all(tables=['timetables'], start_date=START, end_date=END)
download_all(tables=['journeys'], start_date=START, end_date=END)

2026-04-11 19:09:46,896 [INFO] file_cache is only supported with oauth2client<4.0.0
2026-04-11 19:09:47,393 [INFO] [stations] already exists, overwriting with latest from Drive
2026-04-11 19:09:47,395 [INFO] [stations] downloading stations.parquet …
2026-04-11 19:09:47,998 [INFO] [stations] saved to /home/ntorquet/Documents/time-series/timeseries-analysis/PROJECT/EDA/../data/static/stations.parquet
2026-04-11 19:09:48,402 [INFO] [lines] already exists, overwriting with latest from Drive
2026-04-11 19:09:48,404 [INFO] [lines] downloading lines.parquet …
2026-04-11 19:09:48,933 [INFO] [lines] saved to /home/ntorquet/Documents/time-series/timeseries-analysis/PROJECT/EDA/../data/static/lines.parquet
2026-04-11 19:09:49,391 [INFO] [trains] found 27 file(s) in Drive
2026-04-11 19:09:49,396 [INFO] file_cache is only supported with oauth2client<4.0.0
2026-04-11 19:09:49,902 [INFO] [stations] already exists, overwriting with latest from Drive
2026-04-11 19:09:49,903 [INFO] [stations] downloading stations.parquet …
2026-04-11 19:09:50,413 [INFO] [stations] saved to /home/ntorquet/Documents/time-series/timeseries-analysis/PROJECT/EDA/../data/static/stations.parquet
2026-04-11 19:09:50,781 [INFO] [trains] found 27 file(s) in Drive
2026-04-11 19:09:51,154 [INFO] [timetables] found 27 file(s) in Drive
2026-04-11 19:09:51,528 [INFO] [journeys] found 27 file(s) in Drive
2026-04-11 19:09:51,956 [INFO] [weather] found 27 file(s) in Drive
2026-04-11 19:09:51,960 [INFO] file_cache is only supported with oauth2client<4.0.0
2026-04-11 19:09:52,484 [INFO] [stations] already exists, overwriting with latest from Drive
2026-04-11 19:09:52,487 [INFO] [stations] downloading stations.parquet …
2026-04-11 19:09:52,956 [INFO] [stations] saved to /home/ntorquet/Documents/time-series/timeseries-analysis/PROJECT/EDA/../data/static/stations.parquet
2026-04-11 19:09:53,406 [INFO] [lines] already exists, overwriting with latest from Drive
2026-04-11 19:09:53,408 [INFO] [lines] downloading lines.parquet …
2026-04-11 19:09:53,967 [INFO] [lines] saved to /home/ntorquet/Documents/time-series/timeseries-analysis/PROJECT/EDA/../data/static/lines.parquet
2026-04-11 19:09:54,429 [INFO] [timetables] found 27 file(s) in Drive
2026-04-11 19:09:54,435 [INFO] file_cache is only supported with oauth2client<4.0.0
2026-04-11 19:09:54,993 [INFO] [stations] already exists, overwriting with latest from Drive
2026-04-11 19:09:54,996 [INFO] [stations] downloading stations.parquet …
2026-04-11 19:09:55,514 [INFO] [stations] saved to /home/ntorquet/Documents/time-series/timeseries-analysis/PROJECT/EDA/../data/static/stations.parquet
2026-04-11 19:09:55,924 [INFO] [lines] already exists, overwriting with latest from Drive
2026-04-11 19:09:55,925 [INFO] [lines] downloading lines.parquet …
2026-04-11 19:09:56,448 [INFO] [lines] saved to /home/ntorquet/Documents/time-series/timeseries-analysis/PROJECT/EDA/../data/static/lines.parquet
2026-04-11 19:09:56,852 [INFO] [journeys] found 27 file(s) in Drive

In [16]:
from loader import load_trains, load_timetables, load_journeys, load_weather

df_trains = load_trains(start_date=START, end_date=END)
print(f"Shape: {df_trains.shape}")
df_trains.head()

2026-04-11 19:11:09,092 [INFO] Loaded 173924 R1 train rows from 1 file(s)

Shape: (173924, 12)

,train_id,line_id,current_station_id,next_station_id,platform,status,delay_minutes,observations,timestamp,timestamp_minute,position_lat,position_lon
0,25602,R1,79412,79603,2,on_time,0,,2026-04-10 02:58:59,2026-04-10 02:58,41.560764,2.533921
1,25602,R1,78804,79603,2,on_time,0,,2026-04-10 02:58:59,2026-04-10 02:58,41.503155,2.423156
2,25602,R1,79408,79603,2,on_time,0,,2026-04-10 02:58:59,2026-04-10 02:58,41.546760,2.492575
3,25602,R1,79600,79603,2,on_time,0,,2026-04-10 02:58:59,2026-04-10 02:58,41.596008,2.607685
4,25602,R1,79009,79603,3,on_time,0,,2026-04-10 02:58:59,2026-04-10 02:58,41.512527,2.427627

In [48]:
df_timetables = load_timetables(start_date=START, end_date=END)
print(f"Shape: {df_timetables.shape}")
df_timetables.head()

2026-04-11 20:51:36,060 [INFO] Loaded 769738 R1 timetable rows from 1 file(s)

Shape: (769738, 12)

,train_id,station_id,planned_arrival,planned_departure,actual_arrival,actual_departure,platform,stop_type,observations,timestamp,stop_sequence,composition
0,25684,79406,2026-04-09 00:00:00,2026-04-08,2026-04-09 00:09:00,2026-04-08 00:09:00,2,C,,2026-04-08 20:17:39,NaN,None
1,77566,72301,2026-04-08 23:57:00,2026-04-08,2026-04-09 00:33:00,2026-04-08 00:36:00,1,C,,2026-04-08 21:20:13,NaN,None
2,77464,72210,2026-04-08 00:00:00,2026-04-08,2026-04-08 00:47:00,2026-04-08 00:47:00,4,C,,2026-04-08 21:20:13,NaN,None
3,77656,72302,2026-04-08 20:29:13,2026-04-08,2026-04-08 20:29:13,2026-04-08 00:00:00,2,C,,2026-04-08 20:10:13,5.0,true
4,25682,79410,2026-04-08 23:57:00,2026-04-08,2026-04-08 23:59:00,2026-04-08 00:02:00,2,C,,2026-04-08 19:58:53,NaN,None

In [18]:
df_journeys = load_journeys(start_date=START, end_date=END)
print(f"Shape: {df_journeys.shape}")
df_journeys.head()

2026-04-11 19:12:30,863 [INFO] Loaded 74941 R1 journey rows from 1 file(s)

Shape: (74941, 11)

,journey_id,train_id,origin_station_id,destination_station_id,departure_time,arrival_time,duration,accessible,steps,timestamp,duration_minutes
0,77768_72305_72209_2026-04-10 00:00:00,77768,72305,72209,2026-04-10 00:00:00,2026-04-10 00:33:00,0 days 00:33:00,False,1,2026-04-10 01:00:00,33.0
1,77768_72305_72300_2026-04-10 00:00:00,77768,72305,72300,2026-04-10 00:00:00,2026-04-10 00:17:00,0 days 00:17:00,False,1,2026-04-10 00:18:44,17.0
2,25795_79403_79407_2026-04-10 00:01:00,25795,79403,79407,2026-04-10 00:01:00,2026-04-10 00:11:00,0 days 00:10:00,True,1,2026-04-10 22:54:16,10.0
3,25693_79600_79608_2026-04-10 00:01:00,25693,79600,79608,2026-04-10 00:01:00,2026-04-10 00:22:00,0 days 00:21:00,True,1,2026-04-10 23:57:39,21.0
4,25472_71801_79009_2026-04-10 00:01:00,25472,71801,79009,2026-04-10 00:01:00,2026-04-10 00:09:00,0 days 00:08:00,True,1,2026-04-10 19:40:14,8.0

In [19]:
df_weather = load_weather(start_date=START, end_date=END)
print(f"Shape: {df_weather.shape}")
df_weather.head()

2026-04-11 19:12:57,039 [INFO] Loaded 37 weather rows from 1 file(s)

Shape: (37, 7)

,timestamp,timestamp_minute,temperature,precipitation,windspeed,weathercode,cloudcover
0,2026-04-10 00:30:59,2026-04-10 00:30,16.8,0.0,2.6,2,80
1,2026-04-10 00:40:12,2026-04-10 00:40,16.8,0.0,2.6,2,80
2,2026-04-10 01:00:25,2026-04-10 01:00,16.6,0.0,3.5,2,49
3,2026-04-10 01:20:43,2026-04-10 01:20,16.4,0.0,3.9,2,49
4,2026-04-10 02:00:40,2026-04-10 02:00,15.8,0.0,4.5,0,0

![alt text](img/r1_stations.gif "Title")

In [ ]:
# first i want to match each station_id to the actual station name, and get the coordinates of each station
# this will allow me to visualize the data on a map, and also to get the distance between stations
unique_stations = pd.concat([df_timetables["station_id"], df_journeys["origin_station_id"], df_journeys["destination_station_id"]]).unique()
print(f"Number of unique stations: {len(unique_stations)}")
print(f"Unique station ids: {unique_stations}")

Number of unique stations: 39
Unique station ids: <StringArray>
['79406', '72301', '72210', '72302', '79410', '71801', '79403', '78804',
 '79408', '72305', '79500', '79409', '78805', '72211', '79601', '79600',
 '72209', '72303', '79502', '79605', '79412', '79407', '72300', '72205',
 '72204', '79009', '79606', '79603', '79405', '79404', '72207', '79608',
 '79200', '79501', '79604', '79602', '72208', '72206', '79607']
Length: 39, dtype: string

In [33]:
df_station_codes = pd.read_csv("station_codes.csv", dtype=str)
station_id_to_name = dict(zip(df_station_codes["CÓDIGO"], df_station_codes["DESCRIPCION"]))
df_r1_stations = df_station_codes[df_station_codes["CÓDIGO"].isin(unique_stations)][["CÓDIGO", "DESCRIPCION", "LATITUD", "LONGITUD"]].copy()
for station_id in unique_stations:
    if station_id not in station_id_to_name:
        print(f"Station id {station_id} not found in station codes") # yay! all found

# create dataframe with station_id, station_name, latitude, longitude, station_order
df_r1_stations.rename(columns={"CÓDIGO": "station_id", "DESCRIPCION": "station_name", "LATITUD": "latitude", "LONGITUD": "longitude"}, inplace=True)
df_r1_stations["station_order"] = ""
print(df_r1_stations["station_name"].unique())

['ARC DE TRIOMF' 'ARENYS DE MAR' 'BADALONA' 'BARCELONA-CLOT-ARAGO'
 'BARCELONA-SANTS' 'BLANES' 'CABRERA DE MAR-VILASSAR DE MAR'
 "CALDES D'ESTRAC" 'CALELLA' 'CANET DE MAR' 'CASTELLBISBAL' 'CORNELLA'
 'EL MASNOU' 'EL PAPIOL' 'GELIDA' 'LA GRANADA' 'LAVERN-SUBIRATS'
 "L'HOSPITALET DE LLOBREGAT" 'MAÇANET-MASSANES' 'MALGRAT DE MAR'
 'MARTORELL' 'MATARO' 'MOLINS DE REI' 'MONTGAT' 'MONTGAT-NORD' 'OCATA'
 'PINEDA DE MAR' 'PLAÇA  DE CATALUNYA' 'PREMIA DE MAR'
 'SANT ADRIA DE BESOS' 'SANT ANDREU DE LLAVANERES'
 'SANT FELIU DE LLOBREGAT' 'SANT JOAN DESPI' 'SANT POL DE MAR'
 "SANT SADURNI D'ANOIA" 'SANTA SUSANNA' 'TORDERA' 'VILAFRANCA DEL PENEDES'
 'VILASSAR DE MAR']

In [ ]:
# MOLINS DE REI -> 0
# SANT FELIU DE LLOBREGAT -> 1
# SANT JOAN DESPI -> 2
# CORNELLA -> 3
# L'HOSPITALET DE LLOBREGAT -> 4
# BARCELONA-SANTS -> 5
# PLAÇA  DE CATALUNYA -> 6
# ARC DE TRIOMF -> 7
# BARCELONA-CLOT-ARAGO -> 8
# SANT ADRIA DE BESOS -> 9
# BADALONA -> 10
# MONTGAT -> 11
# MONTGAT-NORD -> 12
# EL MASNOU -> 13
# OCATA -> 14
# PREMIA DE MAR -> 15
# VILASSAR DE MAR -> 16
# CABRERA DE MAR-VILASSAR DE MAR -> 17
# MATARO -> 18
# SANT ANDREU DE LLAVANERES -> 19
# CALDES D'ESTRAC -> 20
# ARENYS DE MAR -> 21
# CANET DE MAR -> 22
# SANT POL DE MAR -> 23
# CALELLA -> 24
# PINEDA DE MAR -> 25
# SANTA SUSANNA -> 26
# MALGRAT DE MAR -> 27
# BLANES -> 28
# TORDERA -> 29
# MAÇANET-MASSANES -> 30
df_r1_stations["station_order"] = df_r1_stations["station_name"].map({
    "MOLINS DE REI": "0",
    "SANT FELIU DE LLOBREGAT": "1",
    "SANT JOAN DESPI": "2",
    "CORNELLA": "3",
    "L'HOSPITALET DE LLOBREGAT": "4",
    "BARCELONA-SANTS": "5",
    "PLAÇA  DE CATALUNYA": "6",
    "ARC DE TRIOMF": "7",
    "BARCELONA-CLOT-ARAGO": "8",
    "SANT ADRIA DE BESOS": "9",
    "BADALONA": "10",
    "MONTGAT": "11",
    "MONTGAT-NORD": "12",
    "EL MASNOU": "13",
    "OCATA": "14",
    "PREMIA DE MAR": "15",
    "VILASSAR DE MAR": "16",
    "CABRERA DE MAR-VILASSAR DE MAR": "17",
    "MATARO": "18",
    "SANT ANDREU DE LLAVANERES": "19",
    "CALDES D'ESTRAC": "20",
    "ARENYS DE MAR": "21",
    "CANET DE MAR": "22",
    "SANT POL DE MAR": "23",
    "CALELLA": "24",
    "PINEDA DE MAR": "25",
    "SANTA SUSANNA": "26",
    "MALGRAT DE MAR": "27",
    "BLANES": "28",
    "TORDERA": "29",
    "MAÇANET-MASSANES": "30"
})

df_r1_stations

,station_id,station_name,latitude,longitude,station_order
1,78804,ARC DE TRIOMF,41.3924353000000024849214241839945316314697265625,2.18041630000000008493543646181933581829071044...,7
2,79600,ARENYS DE MAR,41.5776846999999989407115208450704813003540039...,2.54920359999999979194740262755658477544784545...,21
3,79404,BADALONA,41.4458406999999979802851157728582620620727539...,2.24889070000000002025331014010589569807052612...,10
7,79009,BARCELONA-CLOT-ARAGO,41.409599200000002383603714406490325927734375,2.19052569999999979799554239434655755758285522...,8
11,71801,BARCELONA-SANTS,41.379334999999997535269358195364475250244140625,2.13947729999999980421421241771895438432693481...,5
13,79606,BLANES,41.6737575000000006752998160663992166519165039...,2.76904700000000003612399268604349344968795776...,28
15,79412,CABRERA DE MAR-VILASSAR DE MAR,41.5068640000000002032720658462494611740112304...,2.40134330000000018046080185740720480680465698...,17
17,79502,CALDES D'ESTRAC,41.5685223999999990951437212061136960983276367...,2.52715289999999992431867212872020900249481201...,20
18,79603,CALELLA,41.6147386999999966405994200613349676132202148...,2.66562140000000002970637069665826857089996337...,24
20,79601,CANET DE MAR,41.586560800000000881482264958322048187255859375,2.58110470000000002954720912384800612926483154...,22
23,72210,CASTELLBISBAL,41.4732576999999977829247654881328344345092773...,1.96790719999999996758788256556726992130279541...,NaN
28,72303,CORNELLA,41.3580326000000013664248399436473846435546875,2.06947759999999991720187608734704554080963134...,3
31,79407,EL MASNOU,41.4770269999999996457518136594444513320922851...,2.31042900000000006599520929739810526371002197...,13
32,72211,EL PAPIOL,41.4354000000000013415046851150691509246826171875,2.00253900000000006897948878759052604436874389...,NaN
39,72208,GELIDA,41.4482157999999998310158844105899333953857421875,1.86477880000000006965876764297718182206153869...,NaN
46,72205,LA GRANADA,41.3639002999999974008460412733256816864013671875,1.73413979999999989800585353805217891931533813...,NaN
51,72206,LAVERN-SUBIRATS,41.3957338000000021338564692996442317962646484375,1.76947879999999990729975252179428935050964355...,NaN
54,72305,L'HOSPITALET DE LLOBREGAT,41.3642070000000003915374691132456064224243164...,2.09866000000000019198864720237907022237777709...,4
56,79200,MAÇANET-MASSANES,41.7072202000000018529135559219866991043090820...,2.71941899999999980863663040508981794118881225...,30
57,79605,MALGRAT DE MAR,41.6386953000000019642357074189931154251098632...,2.73431859999999993249275576090440154075622558...,27
60,72209,MARTORELL,41.4794338999999965267306833993643522262573242...,1.92668050000000001809041805245215073227882385...,NaN
61,79500,MATARO,41.5336789999999993483470461796969175338745117...,2.44544579999999989183834259165450930595397949...,18
62,72300,MOLINS DE REI,41.4106681000000023118445824366062879562377929...,2.02008440000000000225099938688799738883972167...,0
70,79405,MONTGAT,41.4631131000000010544681572355329990386962890625,2.27196029999999993265191733371466398239135742...,11
71,79406,MONTGAT-NORD,41.4688828000000029305738280527293682098388671875,2.28677749999999990748733580403495579957962036...,12
73,79408,OCATA,41.4788284999999987689989211503416299819946289...,2.32001549999999978624032337393146008253097534...,14
76,79604,PINEDA DE MAR,41.62225250000000187355908565223217010498046875,2.69290770000000012629470802494324743747711181...,25
77,78805,PLAÇA DE CATALUNYA,41.3867712999999994849531503859907388687133789...,2.16631000000000017990942069445736706256866455...,6
80,79409,PREMIA DE MAR,41.4876450000000005502442945726215839385986328125,2.35408060000000007860876394261140376329421997...,15
89,79403,SANT ADRIA DE BESOS,41.4245427000000034922777558676898479461669921875,2.23030969999999983954808158159721642732620239...,9
91,79501,SANT ANDREU DE LLAVANERES,41.5552239000000014357283362187445163726806640625,2.49826680000000012071836863469798117876052856...,19
94,72301,SANT FELIU DE LLOBREGAT,41.3836739999999991823642631061375141143798828125,2.0470731999999998151906765997409820556640625,1
95,72302,SANT JOAN DESPI,41.3693000000000026261659513693302869796752929...,2.05931299999999994909671841014642268419265747...,2
98,79602,SANT POL DE MAR,41.6016377999999988901436154264956712722778320...,2.6240904000000000451109372079372406005859375,23
100,72207,SANT SADURNI D'ANOIA,41.4203321999999971581019053701311349868774414...,1.79388980000000008985239219327922910451889038...,NaN
104,79608,SANTA SUSANNA,41.6303640000000001464286469854414463043212890625,2.71637599999999990174615049909334629774093627...,26
109,79607,TORDERA,41.7072202000000018529135559219866991043090820...,2.71941899999999980863663040508981794118881225...,29
119,72204,VILAFRANCA DEL PENEDES,41.3422230999999982259396347217261791229248046875,1.70679920000000007185292361100437119603157043...,NaN
121,79410,VILASSAR DE MAR,41.5005718999999970719727571122348308563232421875,2.38970349999999998047428562131244689226150512...,16

In [46]:
# get only the rows where station_order is not empty
df_r1_stations = df_r1_stations[(df_r1_stations["station_order"] != "") & (df_r1_stations["station_order"].notna())].copy()

df_r1_stations["station_order"] = df_r1_stations["station_order"].astype(int)
df_r1_stations["latitude"] = df_r1_stations["latitude"].astype(float)
df_r1_stations["longitude"] = df_r1_stations["longitude"].astype(float)

df_r1_stations.sort_values("station_order", inplace=True)
df_r1_stations["latitude"] = df_r1_stations["latitude"].round(6)
df_r1_stations["longitude"] = df_r1_stations["longitude"].round(6)

df_r1_stations.reset_index(drop=True, inplace=True)
df_r1_stations.to_csv("r1_stations.csv", index=False)

In [50]:
# from df_timetables, get only those rows where station_id is in df_r1_stations["station_id"]
df_r1_timetables = df_timetables[df_timetables["station_id"].isin(df_r1_stations["station_id"])].copy()
print(f"Shape: {df_r1_timetables.shape}")
df_r1_timetables

Shape: (643640, 12)

,train_id,station_id,planned_arrival,planned_departure,actual_arrival,actual_departure,platform,stop_type,observations,timestamp,stop_sequence,composition
0,25684,79406,2026-04-09 00:00:00,2026-04-08 00:00:00,2026-04-09 00:09:00,2026-04-08 00:09:00,2,C,,2026-04-08 20:17:39,NaN,None
1,77566,72301,2026-04-08 23:57:00,2026-04-08 00:00:00,2026-04-09 00:33:00,2026-04-08 00:36:00,1,C,,2026-04-08 21:20:13,NaN,None
3,77656,72302,2026-04-08 20:29:13,2026-04-08 00:00:00,2026-04-08 20:29:13,2026-04-08 00:00:00,2,C,,2026-04-08 20:10:13,5.0,true
4,25682,79410,2026-04-08 23:57:00,2026-04-08 00:00:00,2026-04-08 23:59:00,2026-04-08 00:02:00,2,C,,2026-04-08 19:58:53,NaN,None
5,77764,71801,2026-04-08 23:00:01,2026-04-08 00:00:01,2026-04-08 23:58:01,2026-04-08 00:58:01,4,C,,2026-04-08 23:24:08,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...
769729,77768,72301,2026-04-11 23:45:00,2026-04-11 23:51:00,2026-04-11 23:58:00,2026-04-12 00:04:00,None,C,,2026-04-10 23:48:27,5.0,false
769730,25693,79606,2026-04-11 23:52:00,2026-04-11 23:53:00,2026-04-12 00:01:00,2026-04-12 00:02:00,None,C,,2026-04-10 22:36:32,8.0,true
769732,25472,79009,2026-04-11 23:52:11,2026-04-11 23:53:11,2026-04-11 23:52:11,2026-04-11 23:53:11,2,C,,2026-04-10 22:28:11,4.0,false
769734,25698,72305,2026-04-11 23:56:00,2026-04-11 23:56:00,2026-04-12 00:00:00,2026-04-12 00:00:00,None,C,,2026-04-10 22:32:13,0.0,true
769737,77766,72303,2026-04-11 00:06:20,2026-04-11 23:58:14,2026-04-11 00:41:20,2026-04-12 00:33:14,1,C,,2026-04-10 23:11:58,1.0,true

,train_id,station_id,planned_arrival,planned_departure,actual_arrival,actual_departure,platform,stop_type,observations,timestamp,stop_sequence,composition
0,25684,79406,2026-04-09 00:00:00,2026-04-08 00:00:00,2026-04-09 00:09:00,2026-04-08 00:09:00,2,C,,2026-04-08 20:17:39,NaN,None
1,77566,72301,2026-04-08 23:57:00,2026-04-08 00:00:00,2026-04-09 00:33:00,2026-04-08 00:36:00,1,C,,2026-04-08 21:20:13,NaN,None
3,77656,72302,2026-04-08 20:29:13,2026-04-08 00:00:00,2026-04-08 20:29:13,2026-04-08 00:00:00,2,C,,2026-04-08 20:10:13,5.0,true
4,25682,79410,2026-04-08 23:57:00,2026-04-08 00:00:00,2026-04-08 23:59:00,2026-04-08 00:02:00,2,C,,2026-04-08 19:58:53,NaN,None
5,77764,71801,2026-04-08 23:00:01,2026-04-08 00:00:01,2026-04-08 23:58:01,2026-04-08 00:58:01,4,C,,2026-04-08 23:24:08,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...
769568,77768,72300,2026-04-11 23:49:07,2026-04-11 00:50:07,2026-04-12 00:02:07,2026-04-11 01:03:07,None,C,,2026-04-10 23:11:58,6.0,false
769569,25795,79407,2026-04-11 22:50:43,2026-04-11 00:51:43,2026-04-11 22:50:43,2026-04-11 00:51:43,1,C,,2026-04-10 22:36:32,4.0,false
769570,77768,72300,2026-04-11 23:51:00,2026-04-11 00:54:00,2026-04-12 00:04:00,2026-04-11 01:07:00,None,C,,2026-04-10 23:48:27,6.0,false
769572,25693,79605,2026-04-11 22:52:27,2026-04-11 00:56:27,2026-04-11 23:01:27,2026-04-11 01:05:27,None,C,,2026-04-10 22:11:26,7.0,true
769576,25795,79405,2026-04-11 20:54:00,2026-04-11 00:59:00,2026-04-11 20:54:00,2026-04-11 00:59:00,1,C,,2026-04-10 22:07:15,2.0,false